version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
cache:
  - packages -> **\packages.config
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test:
  assemblies: MPMTest\bin\Release\MPMTest.dll
artifacts:
- path: MPM/bin/Release/*
  name: Release
