﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MPM.Net.DTO;
using MPM.Core;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace MPM.Net
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIRepositoryAPI : IRepositoryAPI
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIRepositoryAPI(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<IEnumerable<Package>> GetPackages()
        {
            var arguments = new object[] {  };
            return (Task<IEnumerable<Package>>) methodImpls["GetPackages"](Client, arguments);
        }

        public virtual Task<Package> GetPackage(string packageName)
        {
            var arguments = new object[] { packageName };
            return (Task<Package>) methodImpls["GetPackage"](Client, arguments);
        }

        public virtual Task<Build> GetBuild(string packageName,VersionIdentifier buildVersion)
        {
            var arguments = new object[] { packageName,buildVersion };
            return (Task<Build>) methodImpls["GetBuild"](Client, arguments);
        }

    }
}


