var log        = require( "./log" );

var default_headers     = { "Content-Type": "application/json", "Cache-Control": "max-age=0" };
var error_headers       = { "Content-Type": "text/plain",       "Cache-Control": "max-age=0" };

/**
 * Constructor for a Connection.
 * Connection manages an ongoing connection with a client that has requested something from the API.
 * @param {http.IncomingMessage} req - The HTTP request object for the connection.
 * @param {http.ServerResponse} res - The HTTP response object for the connection.
 */
function Connection( req, res ) {
    this.req = req;
    this.res = res;
    this.url = null;
    this.sql = null;

    this._ended = false;
}
module.exports = Connection;

/**
 * Call this if an error occurs.
 * It will log the error to the console and generate the appropriate status code & error document to return to the user.
 * @param {String} message - An error message to display to the user. Defaults to "".
 * @param {Number} code - The HTTP response code to return to the user. Defaults to 500.
 */
Connection.prototype.error = function( message, code ) {
    if( message == undefined ) { message = "";  }
    if( code    == undefined ) { code    = 500; }

    this.end( "HTTP/1.1 " + String( code ) + ": " + message, code, error_headers );
    log.err( "ERROR: " + message );
}

/**
 * Call this if a MySQL error occurs.
 * This will log the MySQL error to the console and call error() with code 500.
 *
 * @param {Object} error - The error generated by MySQL
 */
Connection.prototype.mysql_error = function( error ) {
    this.error( "MySQL error! See server log / console for details." );
    log.err( "DETAILS: " + String( error ) );
}

/**
 * Finalize and terminate the connection.
 * Closes the connection with the MySQL server and closes the HTTP connection.
 * If the connection has already been closed, does nothing.
 * @param {String} body - The body of the document to return to the user.
 * @param {Number} code - Response code to return to the user. Defaults to 200 (OK).
 * @param {Object} headers - Response headers to return to the user. Defaults to default_headers.
 */
Connection.prototype.end = function( body, code, headers ) {
    if( this._ended )
        return;

    if( code    == undefined ) { code    = 200;             }
    if( headers == undefined ) { headers = default_headers; }

    //Ensure database connection is closed
    if( this.sql != null ) {
        this.sql.end();
        this.sql = null;
    }

    //Write headers and send the body of the message back to the client
    this.res.writeHeader( code, headers );
    this.res.end( body );

    this._ended = true;
}